// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAozaFiwpPqIuysxgltQ0eMLCf5cBjaf2s',
    appId: '1:833901646451:web:8bef431b718f3df7dc1006',
    messagingSenderId: '833901646451',
    projectId: 'buddy-ai-c8f1d',
    authDomain: 'buddy-ai-c8f1d.firebaseapp.com',
    storageBucket: 'buddy-ai-c8f1d.firebasestorage.app',
    measurementId: 'G-HF105ZSGW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ32xzVND1oNzZ1J3C-y_ry6pTFcbCoHM',
    appId: '1:833901646451:android:5c81bc3506d43a61dc1006',
    messagingSenderId: '833901646451',
    projectId: 'buddy-ai-c8f1d',
    storageBucket: 'buddy-ai-c8f1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxv_Iw3XG9ruQMvEdgtU-qbrhuQCqc3GU',
    appId: '1:833901646451:ios:70e0db45761a9c66dc1006',
    messagingSenderId: '833901646451',
    projectId: 'buddy-ai-c8f1d',
    storageBucket: 'buddy-ai-c8f1d.firebasestorage.app',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxv_Iw3XG9ruQMvEdgtU-qbrhuQCqc3GU',
    appId: '1:833901646451:ios:70e0db45761a9c66dc1006',
    messagingSenderId: '833901646451',
    projectId: 'buddy-ai-c8f1d',
    storageBucket: 'buddy-ai-c8f1d.firebasestorage.app',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAozaFiwpPqIuysxgltQ0eMLCf5cBjaf2s',
    appId: '1:833901646451:web:b279d2f5fb29ae2cdc1006',
    messagingSenderId: '833901646451',
    projectId: 'buddy-ai-c8f1d',
    authDomain: 'buddy-ai-c8f1d.firebaseapp.com',
    storageBucket: 'buddy-ai-c8f1d.firebasestorage.app',
    measurementId: 'G-7G375CT5LR',
  );
}
